"""revert_agent_tools_connector_fk_to_blocking

Revision ID: 256fbd77f6b1
Revises: a5335eefa7e0
Create Date: 2026-08-26 14:10:06.293970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.* for SQLModel string columns


# revision identifiers, used by Alembic.
revision: str = '256fbd77f6b1'
down_revision: Union[str, Sequence[str], None] = 'a5335eefa7e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agent_tools_connector_id_fkey'), 'agent_tools', type_='foreignkey')
    op.create_foreign_key(None, 'agent_tools', 'connectors', ['connector_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_tools', type_='foreignkey')
    op.create_foreign_key(op.f('agent_tools_connector_id_fkey'), 'agent_tools', 'connectors', ['connector_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
