"""approvals

Revision ID: 3aecfc5dd347
Revises: b20ff8e66743
Create Date: 2026-08-26 22:11:39.892302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.* for SQLModel string columns
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3aecfc5dd347'
down_revision: Union[str, Sequence[str], None] = 'b20ff8e66743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The SessionStatus enum already exists in the DB; ALTER TYPE adds the new value.
    op.execute("ALTER TYPE sessionstatus ADD VALUE IF NOT EXISTS 'waiting_approval'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('tool_call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pending_tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('messages_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', name='approvalstatus'), nullable=False),
    sa.Column('response_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_agent_id'), 'approval_requests', ['agent_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_org_id'), 'approval_requests', ['org_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_session_id'), 'approval_requests', ['session_id'], unique=False)
    op.add_column('agent_tools', sa.Column('approval_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_tools', 'approval_tools')
    op.drop_index(op.f('ix_approval_requests_session_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_org_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_agent_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.execute("DROP TYPE IF EXISTS approvalstatus")
    # Note: removing a value from an existing enum is not supported in Postgres without
    # recreating the type. The waiting_approval value is left on sessionstatus.
