"""add_agent_assist_messages

Revision ID: 3ee90f978a5b
Revises: cfe5c0810802
Create Date: 2026-08-27 12:47:23.965607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.* for SQLModel string columns
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ee90f978a5b'
down_revision: Union[str, Sequence[str], None] = 'cfe5c0810802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_assist_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_assist_messages_agent_id'), 'agent_assist_messages', ['agent_id'], unique=False)
    op.alter_column('agent_processed_items', 'status',
               existing_type=postgresql.ENUM('in_flight', 'permanent', name='processeditemstatus'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_processed_items', 'status',
               existing_type=postgresql.ENUM('in_flight', 'permanent', name='processeditemstatus'),
               server_default=sa.text("'permanent'::processeditemstatus"),
               existing_nullable=False)
    op.drop_index(op.f('ix_agent_assist_messages_agent_id'), table_name='agent_assist_messages')
    op.drop_table('agent_assist_messages')
    # ### end Alembic commands ###
