"""add_agent_publish_snapshots

Revision ID: 4f0aa1193a88
Revises: 3ee90f978a5b
Create Date: 2026-08-27 13:07:46.628232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.* for SQLModel string columns
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f0aa1193a88'
down_revision: Union[str, Sequence[str], None] = '3ee90f978a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_publish_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('published_by', sa.Uuid(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_publish_snapshots_agent_id'), 'agent_publish_snapshots', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_publish_snapshots_org_id'), 'agent_publish_snapshots', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_publish_snapshots_org_id'), table_name='agent_publish_snapshots')
    op.drop_index(op.f('ix_agent_publish_snapshots_agent_id'), table_name='agent_publish_snapshots')
    op.drop_table('agent_publish_snapshots')
    # ### end Alembic commands ###
