"""connector_fk_on_delete_rules

Revision ID: 60353f763e02
Revises: 737aab89b9a3
Create Date: 2026-08-26 14:05:25.248180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.* for SQLModel string columns


# revision identifiers, used by Alembic.
revision: str = '60353f763e02'
down_revision: Union[str, Sequence[str], None] = '737aab89b9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_processed_items', 'connector_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('agent_processed_items_connector_id_fkey'), 'agent_processed_items', type_='foreignkey')
    op.create_foreign_key(None, 'agent_processed_items', 'connectors', ['connector_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('agent_tools_connector_id_fkey'), 'agent_tools', type_='foreignkey')
    op.create_foreign_key(None, 'agent_tools', 'connectors', ['connector_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('inbound_events_connector_id_fkey'), 'inbound_events', type_='foreignkey')
    op.create_foreign_key(None, 'inbound_events', 'connectors', ['connector_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inbound_events', type_='foreignkey')
    op.create_foreign_key(op.f('inbound_events_connector_id_fkey'), 'inbound_events', 'connectors', ['connector_id'], ['id'])
    op.drop_constraint(None, 'agent_tools', type_='foreignkey')
    op.create_foreign_key(op.f('agent_tools_connector_id_fkey'), 'agent_tools', 'connectors', ['connector_id'], ['id'])
    op.drop_constraint(None, 'agent_processed_items', type_='foreignkey')
    op.create_foreign_key(op.f('agent_processed_items_connector_id_fkey'), 'agent_processed_items', 'connectors', ['connector_id'], ['id'])
    op.alter_column('agent_processed_items', 'connector_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
