"""add model column to agents

Revision ID: 7a62fcc8ce68
Revises: 6f4c6589a5c0
Create Date: 2026-08-26 12:35:48.265175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.* for SQLModel string columns


# revision identifiers, used by Alembic.
revision: str = '7a62fcc8ce68'
down_revision: Union[str, Sequence[str], None] = '6f4c6589a5c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default so the NOT NULL add is safe against existing rows; the column is
    # populated by the app from here on, so the default is dropped immediately after.
    op.add_column(
        'agents',
        sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''),
    )
    op.alter_column('agents', 'model', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'model')
    # ### end Alembic commands ###
