"""agent_model_connector_fk_set_null

Revision ID: a5335eefa7e0
Revises: 60353f763e02
Create Date: 2026-08-26 14:07:39.354382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.* for SQLModel string columns


# revision identifiers, used by Alembic.
revision: str = 'a5335eefa7e0'
down_revision: Union[str, Sequence[str], None] = '60353f763e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agents_model_connector_id_fkey'), 'agents', type_='foreignkey')
    op.create_foreign_key(None, 'agents', 'connectors', ['model_connector_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.create_foreign_key(op.f('agents_model_connector_id_fkey'), 'agents', 'connectors', ['model_connector_id'], ['id'])
    # ### end Alembic commands ###
