"""agent knowledge files and chunks

Revision ID: b20ff8e66743
Revises: 256fbd77f6b1
Create Date: 2026-08-26 21:49:47.364061

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.* for SQLModel string columns


# revision identifiers, used by Alembic.
revision: str = 'b20ff8e66743'
down_revision: Union[str, Sequence[str], None] = '256fbd77f6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Needs the pgvector extension installed on the server (postgresql-16-pgvector).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('agent_knowledge_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'ready', 'error', name='knowledgefilestatus'), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_knowledge_files_agent_id'), 'agent_knowledge_files', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_knowledge_files_org_id'), 'agent_knowledge_files', ['org_id'], unique=False)
    op.create_table('agent_knowledge_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['agent_knowledge_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_knowledge_chunks_agent_id'), 'agent_knowledge_chunks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_knowledge_chunks_file_id'), 'agent_knowledge_chunks', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_knowledge_chunks_file_id'), table_name='agent_knowledge_chunks')
    op.drop_index(op.f('ix_agent_knowledge_chunks_agent_id'), table_name='agent_knowledge_chunks')
    op.drop_table('agent_knowledge_chunks')
    op.drop_index(op.f('ix_agent_knowledge_files_org_id'), table_name='agent_knowledge_files')
    op.drop_index(op.f('ix_agent_knowledge_files_agent_id'), table_name='agent_knowledge_files')
    op.drop_table('agent_knowledge_files')
    op.execute("DROP TYPE IF EXISTS knowledgefilestatus")
    # The vector extension is left installed: dropping it would break any other table using it.
